-- ALTER TABLE `institution_type`
--   CHANGE `name` `name` VARCHAR(255) 
--   CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- insert into academiaratingdb.institution_type values(1, "אוניברסיטה")
-- SELECT * FROM institution_type
-- DELETE FROM degree
-- SET FOREIGN_KEY_CHECKS=0
-- DROP TABLE degree	
-- SET SQL_SAFE_UPDATES = 0;
